program SistemaDePedidos;

uses
  Forms,
  uFormPrincipal in '..\..\Forms\Model\uFormPrincipal.pas' {FormPrincipal},
  uFormModelCustom in '..\..\..\Framework\Forms\Model\uFormModelCustom.pas' {FormModelCustom},
  uFrameLookupModel in '..\..\..\Framework\Forms\Model\uFrameLookupModel.pas' {FrameLookupModel: TFrame},
  uFormModel in '..\..\..\Framework\Forms\Model\uFormModel.pas' {FormModel},
  uFormAddModelCustom in '..\..\..\Framework\Forms\Add\uFormAddModelCustom.pas' {FormAddModelCustom},
  uFormAddModel in '..\..\..\Framework\Forms\Add\uFormAddModel.pas' {FormAddModel},
  uFormAddTimeExecuting in '..\..\..\Framework\Forms\Add\uFormAddTimeExecuting.pas' {FormAddTimeExecuting},
  uFormGridCustom in '..\..\..\Framework\Forms\View\uFormGridCustom.pas' {FormGridCustom},
  uFormGrid in '..\..\..\Framework\Forms\View\uFormGrid.pas' {FormGrid},
  uFormViewModelCustom in '..\..\..\Framework\Forms\View\uFormViewModelCustom.pas' {FormViewModelCustom},
  uFormViewModel in '..\..\..\Framework\Forms\View\uFormViewModel.pas' {FormViewModel},
  uFormViewTimeExecuting in '..\..\..\Framework\Forms\View\uFormViewTimeExecuting.pas' {FormViewTimeExecuting},
  uConstantCidade in '..\..\Constant\uConstantCidade.pas',
  uObjectDaoCidade in '..\..\ObjectDao\uObjectDaoCidade.pas' {ObjectDaoCidade: TDataModule},
  uObjectActionCidade in '..\..\ObjectAction\uObjectActionCidade.pas',
  uFormViewCidade in '..\..\Forms\View\uFormViewCidade.pas' {FormViewCidade},
  uFormAddCidade in '..\..\Forms\Add\uFormAddCidade.pas' {FormAddCidade},
  uConstantPais in '..\..\Constant\uConstantPais.pas',
  uObjectDaoPais in '..\..\ObjectDao\uObjectDaoPais.pas' {ObjectDaoPais: TDataModule},
  uObjectActionPais in '..\..\ObjectAction\uObjectActionPais.pas',
  uFormViewPais in '..\..\Forms\View\uFormViewPais.pas' {FormViewPais},
  uFormAddPais in '..\..\Forms\Add\uFormAddPais.pas' {FormAddPais},
  uConstantEstado in '..\..\Constant\uConstantEstado.pas',
  uObjectDaoEstado in '..\..\ObjectDao\uObjectDaoEstado.pas' {ObjectDaoEstado: TDataModule},
  uObjectActionEstado in '..\..\ObjectAction\uObjectActionEstado.pas',
  uFormViewEstado in '..\..\Forms\View\uFormViewEstado.pas' {FormViewEstado},
  uFormAddEstado in '..\..\Forms\Add\uFormAddEstado.pas' {FormAddEstado},
  uConstantPedido in '..\..\Constant\uConstantPedido.pas',
  uObjectDaoPedido in '..\..\ObjectDao\uObjectDaoPedido.pas' {ObjectDaoPedido: TDataModule},
  uObjectActionPedido in '..\..\ObjectAction\uObjectActionPedido.pas',
  uFormViewPedido in '..\..\Forms\View\uFormViewPedido.pas' {FormViewPedido},
  uFormAddPedido in '..\..\Forms\Add\uFormAddPedido.pas' {FormAddPedido},
  uConstantItemPedido in '..\..\Constant\uConstantItemPedido.pas',
  uObjectDaoItemPedido in '..\..\ObjectDao\uObjectDaoItemPedido.pas' {ObjectDaoItemPedido: TDataModule},
  uObjectActionItemPedido in '..\..\ObjectAction\uObjectActionItemPedido.pas',
  uFormViewItemPedido in '..\..\Forms\View\uFormViewItemPedido.pas' {FormViewItemPedido},
  uFormAddItemPedido in '..\..\Forms\Add\uFormAddItemPedido.pas' {FormAddItemPedido},
  uConstantEndereco in '..\..\Constant\uConstantEndereco.pas',
  uObjectDaoEndereco in '..\..\ObjectDao\uObjectDaoEndereco.pas' {ObjectDaoEndereco: TDataModule},
  uObjectActionEndereco in '..\..\ObjectAction\uObjectActionEndereco.pas',
  uFormViewEndereco in '..\..\Forms\View\uFormViewEndereco.pas' {FormViewEndereco},
  uFormAddEndereco in '..\..\Forms\Add\uFormAddEndereco.pas' {FormAddEndereco},
  uConstantPessoa in '..\..\Constant\uConstantPessoa.pas',
  uObjectDaoPessoa in '..\..\ObjectDao\uObjectDaoPessoa.pas' {ObjectDaoPessoa: TDataModule},
  uObjectActionPessoa in '..\..\ObjectAction\uObjectActionPessoa.pas',
  uFormViewPessoa in '..\..\Forms\View\uFormViewPessoa.pas' {FormViewPessoa},
  uFormAddPessoa in '..\..\Forms\Add\uFormAddPessoa.pas' {FormAddPessoa},
  uConstantProduto in '..\..\Constant\uConstantProduto.pas',
  uObjectDaoProduto in '..\..\ObjectDao\uObjectDaoProduto.pas' {ObjectDaoProduto: TDataModule},
  uObjectActionProduto in '..\..\ObjectAction\uObjectActionProduto.pas',
  uFormViewProduto in '..\..\Forms\View\uFormViewProduto.pas' {FormViewProduto},
  uFormAddProduto in '..\..\Forms\Add\uFormAddProduto.pas' {FormAddProduto},
  uConstantSituacaoPedido in '..\..\Constant\uConstantSituacaoPedido.pas',
  uObjectDaoSituacaoPedido in '..\..\ObjectDao\uObjectDaoSituacaoPedido.pas' {ObjectDaoSituacaoPedido: TDataModule},
  uObjectActionSituacaoPedido in '..\..\ObjectAction\uObjectActionSituacaoPedido.pas',
  uFormViewSituacaoPedido in '..\..\Forms\View\uFormViewSituacaoPedido.pas' {FormViewSituacaoPedido},
  uFormAddSituacaoPedido in '..\..\Forms\Add\uFormAddSituacaoPedido.pas' {FormAddSituacaoPedido},
  uConstantTipo in '..\..\Constant\uConstantTipo.pas',
  uObjectDaoTipo in '..\..\ObjectDao\uObjectDaoTipo.pas' {ObjectDaoTipo: TDataModule},
  uObjectActionTipo in '..\..\ObjectAction\uObjectActionTipo.pas',
  uFormViewTipo in '..\..\Forms\View\uFormViewTipo.pas' {FormViewTipo},
  uFormAddTipo in '..\..\Forms\Add\uFormAddTipo.pas' {FormAddTipo},
  uConstantTipoPessoa in '..\..\Constant\uConstantTipoPessoa.pas',
  uObjectDaoTipoPessoa in '..\..\ObjectDao\uObjectDaoTipoPessoa.pas' {ObjectDaoTipoPessoa: TDataModule},
  uObjectActionTipoPessoa in '..\..\ObjectAction\uObjectActionTipoPessoa.pas',
  uFormViewTipoPessoa in '..\..\Forms\View\uFormViewTipoPessoa.pas' {FormViewTipoPessoa},
  uFormAddTipoPessoa in '..\..\Forms\Add\uFormAddTipoPessoa.pas' {FormAddTipoPessoa},
  uObjectDaoCustom in '..\..\..\Framework\ObjectDao\uObjectDaoCustom.pas' {ObjectDaoCustom: TDataModule},
  uObjectDao in '..\..\..\Framework\ObjectDao\uObjectDao.pas' {ObjectDao: TDataModule},
  uObjectDaoApplication in '..\..\..\Framework\ObjectDao\uObjectDaoApplication.pas' {ObjectDaoApplication: TDataModule},
  uObjectDaoAplicacaoPedidos in '..\..\ObjectDao\uObjectDaoAplicacaoPedidos.pas';

{$R *.res}

begin
  Application.Initialize;
  Application.Title := 'Sistema de Pedidos';
  Application.CreateForm(TFormPrincipal, FormPrincipal);
  Application.CreateForm(TObjectDaoAplicacaoPedidos, ObjectDaoApplication);
  Application.Run;
end.
